[package]
name = "ketbin_utils_syntax"
version = "0.1.0"
authors = ["SphericalKat <amolele@gmail.com>"]
edition = "2018"

[lib]
name = "ketbin_utils_syntax"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = { version = "*", features = ["nif_version_2_17"] }
syntect = "4.6"
